version: "3.9"

services:
  ph-meta-db:
    image: postgres:16
    container_name: ph-meta-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ~/ph-meta-db:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
  ph-qdrant-db:
    build:
      context: .
      dockerfile: qdrant.Dockerfile
    container_name: ph-qdrant-db
    restart: unless-stopped
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC
    environment:
      QDRANT__STORAGE__STORAGE_PATH: /qdrant/storage
    volumes:
      - ~/ph-meta-qdrant:/qdrant/storage